title: Jay Fuller - Portfolio
url: "http://yourdomain.com"
markdown: kramdown
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
